spring:
  application:
    name: spring-ai-practice
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: user
    password: password